# Generated by Django 3.0.8 on 2020-07-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20200724_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Quiz'),
        ),
    ]
