# Generated by Django 3.0.8 on 2020-07-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0002_auto_20200725_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='answer_order',
        ),
    ]
